/**
 * Message and content types for LLM communication.
 * Based on OpenAI types, adapted for Browser Use.
 */

// ============================================================================
// Content Parts
// ============================================================================

function truncate(text: string, maxLength: number = 50): string {
	if (text.length <= maxLength) {
		return text;
	}
	return text.substring(0, maxLength - 3) + '...';
}

function formatImageUrl(url: string, maxLength: number = 50): string {
	if (url.startsWith('data:')) {
		const mediaType = url.includes(';')
			? url.split(';')[0].split(':')[1]
			: 'image';
		return `<base64 ${mediaType}>`;
	}
	return truncate(url, maxLength);
}

export interface ContentPartTextParam {
	type: 'text';
	text: string;
}

export interface ContentPartRefusalParam {
	type: 'refusal';
	refusal: string;
}

export type SupportedImageMediaType =
	| 'image/jpeg'
	| 'image/png'
	| 'image/gif'
	| 'image/webp';

export interface ImageURL {
	/** Either a URL of the image or the base64 encoded image data */
	url: string;
	/** Specifies the detail level of the image */
	detail?: 'auto' | 'low' | 'high';
	/** Media type - needed for Anthropic */
	mediaType?: SupportedImageMediaType;
}

export interface ContentPartImageParam {
	type: 'image_url';
	imageUrl: ImageURL;
}

export type ContentPart =
	| ContentPartTextParam
	| ContentPartImageParam
	| ContentPartRefusalParam;

// ============================================================================
// Function/Tool Call Types
// ============================================================================

export interface FunctionCall {
	/** The name of the function to call */
	name: string;
	/**
	 * The arguments to call the function with, as generated by the model in JSON
	 * format. Note that the model does not always generate valid JSON, and may
	 * hallucinate parameters not defined by your function schema.
	 */
	arguments: string;
}

export interface ToolCall {
	/** The ID of the tool call */
	id: string;
	/** The type of the tool. Currently, only 'function' is supported */
	type: 'function';
	/** The function that the model called */
	function: FunctionCall;
}

// ============================================================================
// Message Types
// ============================================================================

interface MessageBase {
	role: 'user' | 'system' | 'assistant';
	/** Whether to cache this message (Anthropic only) */
	cache?: boolean;
}

export interface UserMessage extends MessageBase {
	role: 'user';
	content: string | ContentPart[];
	name?: string;
}

export interface SystemMessage extends MessageBase {
	role: 'system';
	content: string | ContentPartTextParam[];
	name?: string;
}

export interface AssistantMessage extends MessageBase {
	role: 'assistant';
	content?: string | (ContentPartTextParam | ContentPartRefusalParam)[] | null;
	name?: string;
	refusal?: string | null;
	toolCalls?: ToolCall[];
}

export type BaseMessage = UserMessage | SystemMessage | AssistantMessage;

// ============================================================================
// Helper Functions
// ============================================================================

export function getMessageText(message: BaseMessage): string {
	if (!message.content) {
		return '';
	}

	if (typeof message.content === 'string') {
		return message.content;
	}

	if (Array.isArray(message.content)) {
		return message.content
			.filter((part) => part.type === 'text')
			.map((part) => (part as ContentPartTextParam).text)
			.join('\n');
	}

	return '';
}

export function createTextContent(text: string): ContentPartTextParam {
	return { type: 'text', text };
}

export function createImageContent(
	url: string,
	detail: 'auto' | 'low' | 'high' = 'auto',
	mediaType: SupportedImageMediaType = 'image/png'
): ContentPartImageParam {
	return {
		type: 'image_url',
		imageUrl: { url, detail, mediaType },
	};
}

export function createUserMessage(
	content: string | ContentPart[],
	name?: string
): UserMessage {
	return {
		role: 'user',
		content,
		name,
	};
}

export function createSystemMessage(
	content: string | ContentPartTextParam[],
	name?: string
): SystemMessage {
	return {
		role: 'system',
		content,
		name,
	};
}

export function createAssistantMessage(
	content: string | (ContentPartTextParam | ContentPartRefusalParam)[] | null,
	toolCalls?: ToolCall[],
	name?: string
): AssistantMessage {
	return {
		role: 'assistant',
		content,
		toolCalls,
		name,
	};
}
