/**
 * Browser profile and launch configuration
 */

import os from 'os';
import path from 'path';
import { tmpdir } from 'os';
import { mkdtempSync, mkdirSync, existsSync, readFileSync, writeFileSync, readdirSync, statSync, unlinkSync, rmdirSync, copyFileSync, rmSync } from 'fs';
import fs from 'fs/promises';
import { URL } from 'url';
import { z } from 'zod';
import { v4 as uuidv4 } from 'uuid';
import { execSync } from 'child_process';
import AdmZip from 'adm-zip';
import { logPrettyPath } from '../utils.js';
import { loadStorageState, getDefaultProfilePath, hasImportedProfile } from './profile-import.js';
import { getConfig } from '../config.js';

// ============================================================================
// Constants
// ============================================================================

export const CHROME_DEBUG_PORT = 9242; // use a non-default port to avoid conflicts

export const DOMAIN_OPTIMIZATION_THRESHOLD = 100; // Convert domain lists to sets for O(1) lookup

export const CHROME_DISABLED_COMPONENTS = [
	// Playwright defaults + our additions
	'AcceptCHFrame',
	'AutoExpandDetailsElement',
	'AvoidUnnecessaryBeforeUnloadCheckSync',
	'CertificateTransparencyComponentUpdater',
	'DestroyProfileOnBrowserClose',
	'DialMediaRouteProvider',
	'ExtensionManifestV2Disabled',
	'GlobalMediaControls',
	'HttpsUpgrades',
	'ImprovedCookieControls',
	'LazyFrameLoading',
	'LensOverlay',
	'MediaRouter',
	'PaintHolding',
	'ThirdPartyStoragePartitioning',
	'Translate',
	// Added by us:
	'AutomationControlled',
	'BackForwardCache',
	'OptimizationHints',
	'ProcessPerSiteUpToMainFrameThreshold',
	'InterestFeedContentSuggestions',
	'CalculateNativeWinOcclusion',
	'HeavyAdPrivacyMitigations',
	'PrivacySandboxSettings4',
	'AutofillServerCommunication',
	'CrashReporting',
	'OverscrollHistoryNavigation',
	'InfiniteSessionRestore',
	'ExtensionDisableUnsupportedDeveloper',
	'ExtensionManifestV2Unsupported',
];

export const CHROME_HEADLESS_ARGS = ['--headless=new'];

export const CHROME_DOCKER_ARGS = [
	'--no-sandbox',
	'--disable-gpu-sandbox',
	'--disable-setuid-sandbox',
	'--disable-dev-shm-usage',
	'--no-xshm',
	'--no-zygote',
	'--disable-site-isolation-trials',
];

export const CHROME_DISABLE_SECURITY_ARGS = [
	'--disable-site-isolation-trials',
	'--disable-web-security',
	'--disable-features=IsolateOrigins,site-per-process',
	'--allow-running-insecure-content',
	'--ignore-certificate-errors',
	'--ignore-ssl-errors',
	'--ignore-certificate-errors-spki-list',
];

export const CHROME_DETERMINISTIC_RENDERING_ARGS = [
	'--deterministic-mode',
	'--js-flags=--random-seed=1157259159',
	'--force-device-scale-factor=2',
	'--enable-webgl',
	'--font-render-hinting=none',
	'--force-color-profile=srgb',
];

export const CHROME_DEFAULT_ARGS = [
	'--disable-field-trial-config',
	'--disable-background-networking',
	'--disable-background-timer-throttling',
	'--disable-backgrounding-occluded-windows',
	'--disable-back-forward-cache',
	'--disable-breakpad',
	'--disable-client-side-phishing-detection',
	'--disable-component-extensions-with-background-pages',
	'--disable-component-update',
	'--no-default-browser-check',
	'--disable-dev-shm-usage',
	'--disable-hang-monitor',
	'--disable-ipc-flooding-protection',
	'--disable-popup-blocking',
	'--disable-prompt-on-repost',
	'--disable-renderer-backgrounding',
	'--metrics-recording-only',
	'--no-first-run',
	'--no-service-autorun',
	'--export-tagged-pdf',
	'--disable-search-engine-choice-screen',
	'--unsafely-disable-devtools-self-xss-warnings',
	'--enable-features=NetworkService,NetworkServiceInProcess',
	'--enable-network-information-downlink-max',
	'--test-type=gpu',
	// '--disable-sync', // Removed to allow Chrome sync for credential persistence
	'--allow-legacy-extension-manifests',
	'--allow-pre-commit-input',
	'--disable-blink-features=AutomationControlled',
	'--install-autogenerated-theme=0,0,0',
	'--log-level=2',
	'--disable-focus-on-load',
	'--disable-window-activation',
	'--generate-pdf-document-outline',
	'--no-pings',
	'--ash-no-nudges',
	'--disable-infobars',
	'--simulate-outdated-no-au="Tue, 31 Dec 2099 23:59:59 GMT"',
	'--hide-crash-restore-bubble',
	'--suppress-message-center-popups',
	'--disable-domain-reliability',
	'--disable-datasaver-prompt',
	'--disable-speech-synthesis-api',
	'--disable-speech-api',
	'--disable-print-preview',
	'--safebrowsing-disable-auto-update',
	'--disable-external-intent-requests',
	'--disable-desktop-notifications',
	'--noerrdialogs',
	'--silent-debugger-extension-api',
	'--disable-extensions-http-throttling',
	'--extensions-on-chrome-urls',
	'--disable-default-apps',
	`--disable-features=${CHROME_DISABLED_COMPONENTS.join(',')}`,
];

// ============================================================================
// Types and Interfaces
// ============================================================================

export interface ViewportSize {
	width: number;
	height: number;
}

export const ViewportSizeSchema = z.object({
	width: z.number().min(0),
	height: z.number().min(0),
});

export enum RecordHarContent {
	OMIT = 'omit',
	EMBED = 'embed',
	ATTACH = 'attach',
}

export enum RecordHarMode {
	FULL = 'full',
	MINIMAL = 'minimal',
}

export enum BrowserChannel {
	CHROMIUM = 'chromium',
	CHROME = 'chrome',
	CHROME_BETA = 'chrome-beta',
	CHROME_DEV = 'chrome-dev',
	CHROME_CANARY = 'chrome-canary',
	MSEDGE = 'msedge',
	MSEDGE_BETA = 'msedge-beta',
	MSEDGE_DEV = 'msedge-dev',
	MSEDGE_CANARY = 'msedge-canary',
}

export const BROWSERUSE_DEFAULT_CHANNEL = BrowserChannel.CHROMIUM;

export interface ProxySettings {
	/** Proxy URL, e.g. http://host:8080 or socks5://host:1080 */
	server?: string | null;
	/** Comma-separated hosts to bypass, e.g. localhost,127.0.0.1,*.internal */
	bypass?: string | null;
	/** Proxy auth username */
	username?: string | null;
	/** Proxy auth password */
	password?: string | null;
}

// ============================================================================
// Display Detection
// ============================================================================

let cachedDisplaySize: ViewportSize | null = null;

/**
 * Get the display size (cross-platform)
 */
export function getDisplaySize(): ViewportSize | null {
	if (cachedDisplaySize !== null) {
		return cachedDisplaySize;
	}

	// Try platform-specific detection
	try {
		const platform = os.platform();

		if (platform === 'darwin') {
			// macOS - would need native bindings, fall through to default
			// Could use 'node-mac-screen-size' package or electron screen API
		} else if (platform === 'win32' || platform === 'linux') {
			// Windows/Linux - would need screeninfo equivalent
			// Could use 'screeninfo' via Python bridge or electron screen API
		}
	} catch {
		// Fall through to default
	}

	console.debug('No display size detected, using default 1920x1080');
	cachedDisplaySize = { width: 1920, height: 1080 };
	return cachedDisplaySize;
}

/**
 * Returns recommended x, y offsets for window positioning
 */
export function getWindowAdjustments(): [number, number] {
	const platform = os.platform();

	if (platform === 'darwin') {
		// macOS has a small title bar, no border
		return [-4, 24];
	} else if (platform === 'win32') {
		// Windows has a border on the left
		return [-8, 0];
	} else {
		// Linux
		return [0, 0];
	}
}

// ============================================================================
// Validation Functions
// ============================================================================

/**
 * Validate URL format and optionally check for specific schemes
 */
export function validateUrl(url: string, schemes?: string[]): string {
	try {
		const parsed = new URL(url);
		if (!parsed.hostname) {
			throw new Error(`Invalid URL format: ${url}`);
		}
		if (schemes && schemes.length > 0 && !schemes.includes(parsed.protocol.replace(':', ''))) {
			throw new Error(`URL has invalid scheme: ${url} (expected one of ${schemes.join(', ')})`);
		}
		return url;
	} catch (error: any) {
		throw new Error(`Invalid URL: ${url} - ${error.message}`);
	}
}

/**
 * Validate that float is within specified range
 */
export function validateFloatRange(value: number, minVal: number, maxVal: number): number {
	if (value < minVal || value > maxVal) {
		throw new Error(`Value ${value} outside of range ${minVal}-${maxVal}`);
	}
	return value;
}

/**
 * Validate that arg is a valid CLI argument
 */
export function validateCliArg(arg: string): string {
	if (!arg.startsWith('--')) {
		throw new Error(`Invalid CLI argument: ${arg} (should start with --, e.g. --some-key="some value here")`);
	}
	return arg;
}

// ============================================================================
// BrowserProfile Class
// ============================================================================

export interface BrowserProfileOptions {
	// Session/connection configuration
	cdpUrl?: string | null;
	isLocal?: boolean;
	useCloud?: boolean;

	// Browser launch options
	env?: Record<string, string | number | boolean> | null;
	executablePath?: string | null;
	headless?: boolean | null;
	args?: string[];
	ignoreDefaultArgs?: string[] | true;
	channel?: BrowserChannel | null;
	chromiumSandbox?: boolean;
	devtools?: boolean;
	downloadsPath?: string | null;
	tracesDir?: string | null;

	// Context options
	acceptDownloads?: boolean;
	permissions?: string[];
	userAgent?: string | null;
	screen?: ViewportSize | null;
	viewport?: ViewportSize | null;
	noViewport?: boolean | null;
	deviceScaleFactor?: number | null;

	// Recording options
	recordHarContent?: RecordHarContent;
	recordHarMode?: RecordHarMode;
	recordHarPath?: string | null;
	recordVideoDir?: string | null;
	recordVideoSize?: ViewportSize | null;
	recordVideoFramerate?: number;

	// Persistent context options
	userDataDir?: string | null;
	storageState?: string | Record<string, any> | null;

	// Custom options
	disableSecurity?: boolean;
	deterministicRendering?: boolean;
	allowedDomains?: string[] | Set<string> | null;
	prohibitedDomains?: string[] | Set<string> | null;
	blockIpAddresses?: boolean;
	keepAlive?: boolean | null;

	// Proxy settings
	proxy?: ProxySettings | null;

	// Extensions
	enableDefaultExtensions?: boolean;
	cookieWhitelistDomains?: string[];

	// Window configuration
	windowSize?: ViewportSize | null;
	windowPosition?: ViewportSize | null;
	crossOriginIframes?: boolean;
	maxIframes?: number;
	maxIframeDepth?: number;

	// Page load/wait timings
	minimumWaitPageLoadTime?: number;
	waitForNetworkIdlePageLoadTime?: number;
	waitBetweenActions?: number;

	// Network idle settings
	enableAdaptiveNetworkIdle?: boolean;
	networkIdleTime?: number;
	networkIdleMaxInflight?: number;
	networkIdleTimeout?: number;
	networkIdlePollInterval?: number;

	// UI/viewport/DOM
	highlightElements?: boolean;
	domHighlightElements?: boolean;
	filterHighlightIds?: boolean;
	paintOrderFiltering?: boolean;
	interactionHighlightColor?: string;
	interactionHighlightDuration?: number;

	// Downloads
	autoDownloadPdfs?: boolean;

	profileDirectory?: string;
}

export class BrowserProfile {
	// Session/connection configuration
	cdpUrl: string | null = null;
	isLocal: boolean = false;
	useCloud: boolean = false;

	// Browser launch options
	env: Record<string, string | number | boolean> | null = null;
	executablePath: string | null = null;
	headless: boolean | null = null;
	args: string[] = [];
	ignoreDefaultArgs: string[] | true = [
		'--enable-automation',
		'--disable-extensions',
		'--hide-scrollbars',
		'--disable-features=AcceptCHFrame,AutoExpandDetailsElement,AvoidUnnecessaryBeforeUnloadCheckSync,CertificateTransparencyComponentUpdater,DeferRendererTasksAfterInput,DestroyProfileOnBrowserClose,DialMediaRouteProvider,ExtensionManifestV2Disabled,GlobalMediaControls,HttpsUpgrades,ImprovedCookieControls,LazyFrameLoading,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,Translate',
	];
	channel: BrowserChannel | null = null;
	chromiumSandbox: boolean = !process.env.IN_DOCKER;
	devtools: boolean = false;
	downloadsPath: string | null = null;
	tracesDir: string | null = null;

	// Context options
	acceptDownloads: boolean = true;
	permissions: string[] = ['clipboardReadWrite', 'notifications'];
	userAgent: string | null = null;
	screen: ViewportSize | null = null;
	viewport: ViewportSize | null = null;
	noViewport: boolean | null = null;
	deviceScaleFactor: number | null = null;

	// Recording options
	recordHarContent: RecordHarContent = RecordHarContent.EMBED;
	recordHarMode: RecordHarMode = RecordHarMode.FULL;
	recordHarPath: string | null = null;
	recordVideoDir: string | null = null;
	recordVideoSize: ViewportSize | null = null;
	recordVideoFramerate: number = 30;

	// Persistent context options
	userDataDir: string | null = null;
	storageState: string | Record<string, any> | null = null;

	// Custom options
	disableSecurity: boolean = false;
	deterministicRendering: boolean = false;
	allowedDomains: string[] | Set<string> | null = null;
	prohibitedDomains: string[] | Set<string> | null = null;
	blockIpAddresses: boolean = false;
	keepAlive: boolean | null = null;

	// Proxy settings
	proxy: ProxySettings | null = null;

	// Extensions
	enableDefaultExtensions: boolean = true;
	cookieWhitelistDomains: string[] = ['nature.com', 'qatarairways.com'];

	// Window configuration
	windowSize: ViewportSize | null = null;
	windowPosition: ViewportSize | null = { width: 0, height: 0 };
	crossOriginIframes: boolean = true;
	maxIframes: number = 100;
	maxIframeDepth: number = 5;

	// Page load/wait timings
	minimumWaitPageLoadTime: number = 0.25;
	waitForNetworkIdlePageLoadTime: number = 0.5;
	waitBetweenActions: number = 0.1;

	// Network idle settings
	enableAdaptiveNetworkIdle: boolean = true;
	networkIdleTime: number = 0.5;
	networkIdleMaxInflight: number = 2;
	networkIdleTimeout: number = 10.0;
	networkIdlePollInterval: number = 0.1;

	// UI/viewport/DOM
	highlightElements: boolean = true;
	domHighlightElements: boolean = false;
	filterHighlightIds: boolean = true;
	paintOrderFiltering: boolean = true;
	interactionHighlightColor: string = 'rgb(156, 173, 184)';
	interactionHighlightDuration: number = 0.6;

	// Downloads
	autoDownloadPdfs: boolean = true;

	profileDirectory: string = 'Default';

	constructor(options: BrowserProfileOptions = {}) {
		// Apply all options
		Object.assign(this, options);

		// Post-initialization
		this.validateAndInitialize();
	}

	private validateAndInitialize(): void {
		// Validate devtools + headless
		if (this.headless && this.devtools) {
			throw new Error('headless=True and devtools=True cannot both be set at the same time');
		}

		// Set default downloads path
		if (!this.downloadsPath) {
			const uniqueId = uuidv4().substring(0, 8);
			this.downloadsPath = path.join(tmpdir(), `browser-use-downloads-${uniqueId}`);
			if (!existsSync(this.downloadsPath)) {
				fs.mkdir(this.downloadsPath, { recursive: true }).catch(() => {});
			}
		}

		// Set default user data dir - use persistent path for credential/session preservation
		if (!this.userDataDir) {
			const cfg = getConfig();
			this.userDataDir = cfg.BROWSER_USE_DEFAULT_USER_DATA_DIR;
			// Ensure the directory exists
			if (!existsSync(this.userDataDir)) {
				mkdirSync(this.userDataDir, { recursive: true });
			}
			console.log(`[BrowserProfile] Using persistent user data directory: ${logPrettyPath(this.userDataDir)}`);
		}

		// Auto-load storage state from imported profile if not provided
		// This enables Atlas-like autonomous authentication
		if (!this.storageState && hasImportedProfile()) {
			const savedState = loadStorageState();
			if (savedState && savedState.cookies.length > 0) {
				this.storageState = savedState;
				console.log(
					`[BrowserProfile] Auto-loaded ${savedState.cookies.length} cookies from imported profile`
				);
			}
		}

		// Optimize large domain lists
		this.allowedDomains = this.optimizeLargeDomainList(this.allowedDomains);
		this.prohibitedDomains = this.optimizeLargeDomainList(this.prohibitedDomains);

		// Validate proxy settings
		if (this.proxy?.bypass && !this.proxy.server) {
			console.warn('BrowserProfile.proxy.bypass provided but proxy has no server; bypass will be ignored.');
		}

		// Validate highlight elements conflict
		if (this.highlightElements && this.domHighlightElements) {
			console.warn(
				'⚠️ Both highlight_elements and dom_highlight_elements are enabled. dom_highlight_elements takes priority. Setting highlight_elements=False.'
			);
			this.highlightElements = false;
		}

		// Warn about deterministic rendering
		if (this.deterministicRendering) {
			console.warn(
				'⚠️ BrowserSession(deterministic_rendering=True) is NOT RECOMMENDED. It breaks many sites and increases chances of getting blocked.'
			);
		}

		// Detect display configuration
		this.detectDisplayConfiguration();
	}

	private optimizeLargeDomainList(domains: string[] | Set<string> | null): string[] | Set<string> | null {
		if (!domains || domains instanceof Set) {
			return domains;
		}

		if (domains.length >= DOMAIN_OPTIMIZATION_THRESHOLD) {
			console.warn(
				`🔧 Optimizing domain list with ${domains.length} items to set for O(1) lookup. ` +
					`Note: Pattern matching (*.domain.com, etc.) is not supported for lists >= ${DOMAIN_OPTIMIZATION_THRESHOLD} items.`
			);
			return new Set(domains);
		}

		return domains;
	}

	detectDisplayConfiguration(): void {
		const displaySize = getDisplaySize();
		const hasScreenAvailable = !!displaySize;
		this.screen = this.screen || displaySize || { width: 1920, height: 1080 };

		// If no headless preference specified, prefer headful if there is a display available
		if (this.headless === null) {
			this.headless = !hasScreenAvailable;
		}

		// Determine viewport behavior based on mode and user preferences
		const userProvidedViewport = this.viewport !== null;

		if (this.headless) {
			// Headless mode: always use viewport for content size control
			this.viewport = this.viewport || this.windowSize || this.screen;
			this.windowPosition = null;
			this.windowSize = null;
			this.noViewport = false;
		} else {
			// Headful mode: respect user's viewport preference
			this.windowSize = this.windowSize || this.screen;

			if (userProvidedViewport) {
				// User explicitly set viewport - enable viewport mode
				this.noViewport = false;
			} else {
				// Default headful: content fits to window (no viewport)
				this.noViewport = this.noViewport === null ? true : this.noViewport;
			}
		}

		// Handle special requirements (device_scale_factor forces viewport mode)
		if (this.deviceScaleFactor && this.noViewport === null) {
			this.noViewport = false;
		}

		// Finalize configuration
		if (this.noViewport) {
			// No viewport mode: content adapts to window
			this.viewport = null;
			this.deviceScaleFactor = null;
			this.screen = null;
		} else {
			// Viewport mode: ensure viewport is set
			this.viewport = this.viewport || this.screen;
			this.deviceScaleFactor = this.deviceScaleFactor || 1.0;
		}

		// Final validation
		if (this.headless && this.noViewport) {
			throw new Error('headless=True and no_viewport=True cannot both be set at the same time');
		}
	}

	getArgs(): string[] {
		if (!this.userDataDir) {
			throw new Error('user_data_dir must be set');
		}

		// Collect all args
		let defaultArgs: string[] = [];

		if (Array.isArray(this.ignoreDefaultArgs)) {
			defaultArgs = CHROME_DEFAULT_ARGS.filter((arg) => {
				const key = arg.split('=')[0];
				return !(this.ignoreDefaultArgs as string[]).some((ignored) => arg.startsWith(ignored) || key === ignored);
			});
		} else if (this.ignoreDefaultArgs === true) {
			defaultArgs = [];
		} else {
			defaultArgs = [...CHROME_DEFAULT_ARGS];
		}

		const inDocker = !!process.env.IN_DOCKER;

		const preConversionArgs = [
			...defaultArgs,
			...this.args,
			`--user-data-dir=${this.userDataDir}`,
			`--profile-directory=${this.profileDirectory}`,
			...(inDocker || !this.chromiumSandbox ? CHROME_DOCKER_ARGS : []),
			...(this.headless ? CHROME_HEADLESS_ARGS : []),
			...(this.disableSecurity ? CHROME_DISABLE_SECURITY_ARGS : []),
			...(this.deterministicRendering ? CHROME_DETERMINISTIC_RENDERING_ARGS : []),
			...(this.windowSize
				? [`--window-size=${this.windowSize.width},${this.windowSize.height}`]
				: !this.headless
					? ['--start-maximized']
					: []),
			...(this.windowPosition ? [`--window-position=${this.windowPosition.width},${this.windowPosition.height}`] : []),
			...(this.enableDefaultExtensions ? this.getExtensionArgs() : []),
		];

		// Proxy flags
		if (this.proxy?.server) {
			preConversionArgs.push(`--proxy-server=${this.proxy.server}`);
			if (this.proxy.bypass) {
				preConversionArgs.push(`--proxy-bypass-list=${this.proxy.bypass}`);
			}
		}

		// User agent flag
		if (this.userAgent) {
			preConversionArgs.push(`--user-agent=${this.userAgent}`);
		}

		// Merge --disable-features values
		const disableFeaturesValues: string[] = [];
		const nonDisableFeaturesArgs: string[] = [];

		for (const arg of preConversionArgs) {
			if (arg.startsWith('--disable-features=')) {
				const features = arg.split('=', 2)[1];
				disableFeaturesValues.push(...features.split(','));
			} else {
				nonDisableFeaturesArgs.push(arg);
			}
		}

		// Remove duplicates while preserving order
		if (disableFeaturesValues.length > 0) {
			const uniqueFeatures = [...new Set(disableFeaturesValues.map((f) => f.trim()).filter(Boolean))];
			nonDisableFeaturesArgs.push(`--disable-features=${uniqueFeatures.join(',')}`);
		}

		// Convert to dict and back to dedupe
		const finalArgsList = BrowserProfile.argsAsList(BrowserProfile.argsAsDict(nonDisableFeaturesArgs));

		return finalArgsList;
	}

	private getExtensionArgs(): string[] {
		const extensionPaths = this.ensureDefaultExtensionsDownloaded();

		const args = [
			'--enable-extensions',
			'--disable-extensions-file-access-check',
			'--disable-extensions-http-throttling',
			'--enable-extension-activity-logging',
		];

		if (extensionPaths.length > 0) {
			args.push(`--load-extension=${extensionPaths.join(',')}`);
		}

		return args;
	}

	/**
	 * Ensure default extensions are downloaded and cached locally.
	 * Returns list of paths to extension directories.
	 */
	private ensureDefaultExtensionsDownloaded(): string[] {
		// Extension definitions - optimized for automation and content extraction
		const extensions = [
			{
				name: 'uBlock Origin',
				id: 'cjpalhdlnbpafiamejdnhcphjbkeiagm',
				url: 'https://clients2.google.com/service/update2/crx?response=redirect&prodversion=133&acceptformat=crx3&x=id%3Dcjpalhdlnbpafiamejdnhcphjbkeiagm%26uc',
			},
			{
				name: "I still don't care about cookies",
				id: 'edibdbjcniadpccecjdfdjjppcpchdlm',
				url: 'https://clients2.google.com/service/update2/crx?response=redirect&prodversion=133&acceptformat=crx3&x=id%3Dedibdbjcniadpccecjdfdjjppcpchdlm%26uc',
			},
			{
				name: 'ClearURLs',
				id: 'lckanjgmijmafbedllaakclkaicjfmnk',
				url: 'https://clients2.google.com/service/update2/crx?response=redirect&prodversion=133&acceptformat=crx3&x=id%3Dlckanjgmijmafbedllaakclkaicjfmnk%26uc',
			},
			{
				name: 'Force Background Tab',
				id: 'gidlfommnbibbmegmgajdbikelkdcmcl',
				url: 'https://clients2.google.com/service/update2/crx?response=redirect&prodversion=133&acceptformat=crx3&x=id%3Dgidlfommnbibbmegmgajdbikelkdcmcl%26uc',
			},
		];

		// Create extensions cache directory
		const cacheDir = path.join(os.homedir(), '.config', 'browseruse', 'cache', 'extensions');
		try {
			if (!existsSync(cacheDir)) {
				mkdirSync(cacheDir, { recursive: true });
			}
		} catch (e) {
			console.warn(`Failed to create extensions cache directory: ${e}`);
			return [];
		}

		const extensionPaths: string[] = [];
		const loadedExtensionNames: string[] = [];

		for (const ext of extensions) {
			const extDir = path.join(cacheDir, ext.id);
			const crxFile = path.join(cacheDir, `${ext.id}.crx`);

			// Check if extension is already extracted
			if (existsSync(path.join(extDir, 'manifest.json'))) {
				extensionPaths.push(extDir);
				loadedExtensionNames.push(ext.name);
				continue;
			}

			try {
				// Download extension if not cached
				if (!existsSync(crxFile)) {
					console.log(`📦 Downloading ${ext.name} extension...`);
					this.downloadExtensionSync(ext.url, crxFile);
				}

				// Extract extension
				console.log(`📂 Extracting ${ext.name} extension...`);
				this.extractExtensionSync(crxFile, extDir);

				extensionPaths.push(extDir);
				loadedExtensionNames.push(ext.name);
			} catch (e) {
				console.warn(`⚠️ Failed to setup ${ext.name} extension: ${e}`);
				continue;
			}
		}

		// Apply minimal patch to cookie extension with configurable whitelist
		for (let i = 0; i < extensionPaths.length; i++) {
			if (loadedExtensionNames[i] === "I still don't care about cookies") {
				this.applyMinimalExtensionPatch(extensionPaths[i], this.cookieWhitelistDomains);
			}
		}

		if (extensionPaths.length > 0) {
			console.debug(`[BrowserProfile] 🧩 Extensions loaded (${extensionPaths.length}): [${loadedExtensionNames.join(', ')}]`);
		} else {
			console.warn('[BrowserProfile] ⚠️ No default extensions could be loaded');
		}

		return extensionPaths;
	}

	/**
	 * Download extension .crx file (synchronous)
	 */
	private downloadExtensionSync(url: string, outputPath: string): void {
		try {
			// Use curl for reliable downloads with redirect following (execSync imported at top)
			execSync(`curl -L -o "${outputPath}" "${url}"`, { stdio: 'pipe' });
		} catch (e) {
			throw new Error(`Failed to download extension: ${e}`);
		}
	}

	/**
	 * Extract .crx file to directory (synchronous)
	 */
	private extractExtensionSync(crxPath: string, extractDir: string): void {
		// Remove existing directory (using imported rmSync and mkdirSync)
		if (existsSync(extractDir)) {
			rmSync(extractDir, { recursive: true });
		}
		mkdirSync(extractDir, { recursive: true });

		try {
			// Try direct ZIP extraction first
			const zip = new AdmZip(crxPath);
			zip.extractAllTo(extractDir, true);

			// Verify manifest exists
			if (!existsSync(path.join(extractDir, 'manifest.json'))) {
				throw new Error('No manifest.json found in extension');
			}
		} catch (e: any) {
			// CRX files have a header before the ZIP data
			// Skip the CRX header and extract the ZIP part
			const buffer = readFileSync(crxPath);

			// Check CRX magic number
			const magic = buffer.slice(0, 4).toString();
			if (magic !== 'Cr24') {
				throw new Error('Invalid CRX file format');
			}

			// Read version
			const version = buffer.readUInt32LE(4);
			let zipStart: number;

			if (version === 2) {
				const pubkeyLen = buffer.readUInt32LE(8);
				const sigLen = buffer.readUInt32LE(12);
				zipStart = 16 + pubkeyLen + sigLen;
			} else if (version === 3) {
				const headerLen = buffer.readUInt32LE(8);
				zipStart = 12 + headerLen;
			} else {
				throw new Error(`Unsupported CRX version: ${version}`);
			}

			// Extract ZIP data
			const zipData = buffer.slice(zipStart);
			const tempZipPath = crxPath + '.zip';

			try {
				writeFileSync(tempZipPath, zipData);
				const zip = new AdmZip(tempZipPath);
				zip.extractAllTo(extractDir, true);
			} finally {
				if (existsSync(tempZipPath)) {
					unlinkSync(tempZipPath);
				}
			}

			// Verify manifest exists
			if (!existsSync(path.join(extractDir, 'manifest.json'))) {
				throw new Error('No manifest.json found in extension after CRX extraction');
			}
		}
	}

	/**
	 * Apply minimal patch to cookie extension with configurable domain whitelist
	 */
	private applyMinimalExtensionPatch(extDir: string, whitelistDomains: string[]): void {
		const bgPath = path.join(extDir, 'data', 'background.js');

		if (!existsSync(bgPath)) {
			return;
		}

		try {
			let content = readFileSync(bgPath, 'utf-8');

			// Create the whitelisted domains object for JavaScript
			const whitelistEntries = whitelistDomains.map((domain) => `        "${domain}": true`);
			const whitelistJs = '{\n' + whitelistEntries.join(',\n') + '\n      }';

			// Find the initialize() function and inject storage setup
			const oldInit = `async function initialize(checkInitialized, magic) {
  if (checkInitialized && initialized) {
    return;
  }
  loadCachedRules();
  await updateSettings();
  await recreateTabList(magic);
  initialized = true;
}`;

			const newInit = `// Pre-populate storage with configurable domain whitelist if empty
async function ensureWhitelistStorage() {
  const result = await chrome.storage.local.get({ settings: null });
  if (!result.settings) {
    const defaultSettings = {
      statusIndicators: true,
      whitelistedDomains: ${whitelistJs}
    };
    await chrome.storage.local.set({ settings: defaultSettings });
  }
}

async function initialize(checkInitialized, magic) {
  if (checkInitialized && initialized) {
    return;
  }
  loadCachedRules();
  await ensureWhitelistStorage(); // Add storage initialization
  await updateSettings();
  await recreateTabList(magic);
  initialized = true;
}`;

			if (content.includes(oldInit)) {
				content = content.replace(oldInit, newInit);
				writeFileSync(bgPath, content, 'utf-8');
				const domainList = whitelistDomains.join(', ');
				console.log(`[BrowserProfile] ✅ Cookie extension: ${domainList} pre-populated in storage`);
			}
		} catch (e) {
			console.debug(`[BrowserProfile] Could not patch extension storage: ${e}`);
		}
	}

	static argsAsDict(args: string[]): Record<string, string> {
		const argsDict: Record<string, string> = {};
		for (const arg of args) {
			const [key, ...valueParts] = arg.split('=');
			const value = valueParts.join('=');
			argsDict[key.trim().replace(/^-+/, '')] = value.trim();
		}
		return argsDict;
	}

	static argsAsList(args: Record<string, string>): string[] {
		return Object.entries(args).map(([key, value]) =>
			value ? `--${key.replace(/^-+/, '')}=${value}` : `--${key.replace(/^-+/, '')}`
		);
	}

	toString(): string {
		return 'BrowserProfile';
	}

	repr(): string {
		const shortDir = this.userDataDir ? logPrettyPath(this.userDataDir) : '<incognito>';
		return `BrowserProfile(user_data_dir=${shortDir}, headless=${this.headless})`;
	}
}
